default:
  adapter: postgresql
  encoding: unicode
  database: joegattnet_v3
  pool: 5
  host: localhost
  username: postgres
  password: password
 
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
