development:
  adapter: postgresql
  encoding: unicode
  database: joegattnet_v3
  pool: 5
  host: localhost
  username: postgres
  password: password
 
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: joegattnet_v3_staging
  pool: 5
  host: localhost
  username: deployer
  password: itTieni10
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: joegattnet_v3
  pool: 5
  host: localhost
  username: deployer
  password: itTieni10
  port: 5433
