#!/usr/bin/env ruby

# See http://stackoverflow.com/questions/5441221/custom-daemon-with-rails-3
#  and http://stackoverflow.com/questions/4901745/how-to-write-a-robust-never-ending-process

require 'rubygems'
require 'bundler'
require 'daemons'

options = {
  :app_name   => "Nembrot",
  :dir_mode   => :system,
  :multiple   => true,
  :backtrace  => true,
  :monitor    => true
}

script = "#{ENV["APP_ROOT"]}/script/daemons/#{ARGV[1]}"
Daemons.run(script, options)
